### ISSUE TITLE
Recommendations on Variable Names

### ISSUE THREAD

**Issue by Arya-Hari** [Goutami-Sooda/ITRL-Project#1]
The following restrictions are recommended to be placed on variable names - 

1. Kannada equivalents of variables like "digit", "number", etc. should not be used. They produce inconsistencies in translations with translations ranging from "digit" to "numeric" for the same variable name.
2. Ideally one character variables are also not recommended. 
3. Variable type should also ideally be specified by the user. For example, if a floating point variable is required the word "float", "floating" or the phrases "floating point", "with decimal point", etc. should be present in the input. Suitable Kannada algorithms should be provided for these words or phrases to be present in the English translation.

**Note  - There are several inconsistencies in the dataset regarding variable names. I shall upload the modified and correct dataset along with the json file. Please refer to these when considering deployment or running of the NLP model**

**Comment by Goutami-Sooda** [comment]
Thank you for raising these considerations, and I appreciate your insights regarding restrictions on variable names.

I agree with the suggestion to avoid Kannada equivalents of variables like "digit," "number," "sum," etc., as it could lead to inconsistencies in translations. This will help ensure a uniform and reliable translation output.

I understand the concern about using one-character variables, especially where the alphabet 'E' is being translated to "this." However, these are widely adopted and provide a concise representation in many coding contexts. Notably, other commonly used alphabets are being translated accurately, so we can continue using them. Utilizing variable names like var1, var2, num1, num2 may not be feasible due to limitations in translation tools.

I fully support the idea of users explicitly specifying variable types, such as "float" or "floating point," to enhance accuracy and clarity in translations. In fact, many of the algorithms in the dataset already follow this practice.

I am open to discuss and evaluate the feasibility of alternative approaches to name the variables. Looking forward to address these concerns collaboratively in our upcoming discussions!
