### ISSUE TITLE
Incorrect Indentation in Generated Python Code for Loop-related Algorithm

### ISSUE THREAD

**Issue by Goutami-Sooda** [Goutami-Sooda/ITRL-Project#2]
@Arya-Hari 
I have tested the NLP model on Hugging Face with various inputs and i'm pleased to see that it works well for many of the algorithms. But, I found that for algorithms like "print i inside loop," the generated Python code lacks proper indentation. This is crucial, especially for loop-related code. Upon checking the dataset, I noticed that records for this algorithm don't have the correct indentation as in the original dataset created by the team.

I suggest reviewing and correcting the dataset records to ensure accurate representations of code structure. Retraining the model on this corrected dataset should enhance its performance and provide consistent and reliable inferences.  Additionally, I recommend conducting exhaustive testing with various input algorithms to ensure the model's accuracy and reliability.

**Comment by Arya-Hari** [comment]
@Goutami-Sooda Please confirm whether this issue is arising only on the inference API viewer on Hugging Face or in the actual output of the API call in the web application.

 Also, as per my knowledge, the dataset does have the necessary indentation for the looping statements. In case you are referring to the dataset loaded on Hugging Face Hub, please ignore it. The model is currently trained on the json file uploaded in this GitHub repository, in which, as per my knowledge, the statements have correct indentation as I have done it manually. Nonetheless, I'll go through it again to check for inconsistencies.

**Comment by Goutami-Sooda** [comment]
The issue was encountered in the inference API viewer on Hugging Face. To provide further clarification, I specifically referred to the dataset loaded on Hugging Face Hub. 

After integrating the model inference into the web application, I have checked the output of the API call, and in this context, the Python code is appropriately indented.
